version: '3'
services:
  nest-wechaty-bot:
    # 镜像名称
    image: nest-wechaty-bot
    # 容器名称
    container_name: nest-wechaty-bot
    # 自启动
    restart: unless-stopped
    # 设定上下文根目录，然后以该目录为准指定 Dockerfile，赋值Dockerfile 中的 ARG 指令
    build:
      context: .
      dockerfile: Dockerfile
    # 将日志大小限制为 1M，以防止硬盘空间不足
    logging:
      driver: json-file
      options:
        max-size: 1m
    # 加入指定网络
    networks:
      - MyNetwork
    # environment:
    #   - WECHATY_LOG=silly
    ports:
      - 4000:4000
    # volumes:
    #   - ./src:/app/src

networks:
  MyNetwork:
    external: true
# docker-compose build --no-cache
# docker-compose up -d